/**
 * Writes the generated agent definitions next to the skills the Skills CLI has
 * just installed.
 *
 * The Skills CLI installs skills into each tool's skills directory and has no
 * concept of an agent definition, so this step is the CLI's own and runs only
 * on the npm path. A checkout installed with `npx skills add` never reaches
 * this code, which is why `squad-skills agents` exists as its own command.
 *
 * Two rules keep it safe to run repeatedly: a file without the generated marker
 * is never overwritten, and the Codex config is backed up before its first
 * edit in a run.
 */

import { copyFile, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { registerCodexAgents } from './codex-config-registration.ts';
import {
  generatedMarker,
  readSkillAgentDefinition,
  renderClaudeAgentFile,
  renderCodexAgentFile,
} from './skill-agent-definition.ts';

export type AgentScope = 'global' | 'project';

export interface AgentInstallationRequest {
  agents: string[];
  force: boolean;
  homeDirectory: string;
  packageRoot: string;
  projectRoot: string;
  scope: AgentScope;
  skills: string[];
}

export interface AgentInstallationResult {
  messages: string[];
  written: string[];
}

interface AgentTarget {
  agentsDirectory: string;
  codexConfigFile?: string;
  extension: '.md' | '.toml';
  render: (definition: Definition, installedSkillPath: string) => string;
  /**
   * Where the Skills CLI may have put the skill, best candidate first. Codex
   * reads its skills from the shared `.agents/skills` directory rather than
   * from `.codex/skills`, and that has moved between Skills CLI versions, so
   * the location is probed instead of assumed.
   */
  skillsRoots: string[];
  tool: string;
}

type Definition = NonNullable<ReturnType<typeof readSkillAgentDefinition>>;

const supportedTools = new Set(['claude-code', 'codex']);

export async function installAgentDefinitions(
  request: AgentInstallationRequest
): Promise<AgentInstallationResult> {
  const messages: string[] = [];
  const written: string[] = [];
  const definitions = await readDefinitions(request, messages);

  if (definitions.length === 0) return { messages, written };

  for (const tool of request.agents) {
    if (!supportedTools.has(tool)) continue;

    const target = resolveTarget(tool, request);

    if (target === null) {
      messages.push(
        `Skipped ${tool} agents: project scope is not a verified location for them; install with --global.`
      );
      continue;
    }

    await mkdir(target.agentsDirectory, { recursive: true });
    const registered: string[] = [];

    for (const definition of definitions) {
      const installedSkillFile = await findInstalledSkill(target.skillsRoots, definition.name);

      if (installedSkillFile === null) {
        messages.push(`Skipped ${tool}/${definition.name}: the skill is not installed there.`);
        continue;
      }

      const agentFile = path.join(target.agentsDirectory, `${definition.name}${target.extension}`);

      if (!request.force && (await isForeignFile(agentFile))) {
        messages.push(`Kept ${agentFile}: not generated by squad-skills. Use --force to replace.`);
        continue;
      }

      await writeFile(agentFile, target.render(definition, installedSkillFile), 'utf8');
      written.push(agentFile);
      registered.push(definition.name);
    }

    if (target.codexConfigFile !== undefined && registered.length > 0) {
      messages.push(...(await registerInCodexConfig(target.codexConfigFile, registered)));
    }
  }

  return { messages, written };
}

async function readDefinitions(
  request: AgentInstallationRequest,
  messages: string[]
): Promise<Definition[]> {
  const skillsRoot = path.join(request.packageRoot, 'skills');
  const names =
    request.skills.length > 0 ? request.skills : await readSkillDirectories(skillsRoot, messages);
  const definitions: Definition[] = [];

  for (const name of names) {
    let source: string;

    try {
      source = await readFile(path.join(skillsRoot, name, 'SKILL.md'), 'utf8');
    } catch {
      messages.push(`Skipped ${name}: no packaged SKILL.md.`);
      continue;
    }

    const definition = readSkillAgentDefinition(source);

    if (definition === null) {
      messages.push(`Skipped ${name}: SKILL.md frontmatter is missing a name or description.`);
      continue;
    }

    definitions.push(definition);
  }

  return definitions;
}

async function readSkillDirectories(skillsRoot: string, messages: string[]): Promise<string[]> {
  try {
    const entries = await readdir(skillsRoot, { withFileTypes: true });
    return entries
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .sort();
  } catch {
    messages.push(`Skipped every agent: ${skillsRoot} is unreadable.`);
    return [];
  }
}

function resolveTarget(tool: string, request: AgentInstallationRequest): AgentTarget | null {
  const root = request.scope === 'global' ? request.homeDirectory : request.projectRoot;

  if (tool === 'claude-code') {
    return {
      agentsDirectory: path.join(root, '.claude', 'agents'),
      extension: '.md',
      render: renderClaudeAgentFile,
      skillsRoots: [path.join(root, '.claude', 'skills'), path.join(root, '.agents', 'skills')],
      tool,
    };
  }

  // Codex registers agents through a config file whose project-scope location
  // this CLI has not verified, so only the global one is claimed.
  if (request.scope !== 'global') return null;

  return {
    agentsDirectory: path.join(root, '.codex', 'agents'),
    codexConfigFile: path.join(root, '.codex', 'config.toml'),
    extension: '.toml',
    render: renderCodexAgentFile,
    skillsRoots: [path.join(root, '.agents', 'skills'), path.join(root, '.codex', 'skills')],
    tool,
  };
}

async function registerInCodexConfig(configFile: string, names: string[]): Promise<string[]> {
  let source: string;

  try {
    source = await readFile(configFile, 'utf8');
  } catch {
    source = '';
  }

  const result = registerCodexAgents(source, names);

  if (result.added.length === 0) return [];

  if (source.length > 0) await copyFile(configFile, `${configFile}.squad-skills-backup`);
  else await mkdir(path.dirname(configFile), { recursive: true });

  await writeFile(configFile, result.source, 'utf8');

  return [`Registered ${result.added.join(', ')} in ${configFile}.`];
}

async function findInstalledSkill(roots: string[], name: string): Promise<string | null> {
  for (const root of roots) {
    const candidate = path.join(root, name, 'SKILL.md');

    try {
      await readFile(candidate, 'utf8');
      return candidate;
    } catch {
      continue;
    }
  }

  return null;
}

async function isForeignFile(file: string): Promise<boolean> {
  try {
    return !(await readFile(file, 'utf8')).includes(generatedMarker);
  } catch {
    return false;
  }
}
