/**
 * Turns a packaged skill into an agent definition for Claude Code and Codex.
 *
 * The skill is the single source of truth. Nothing here restates a role's
 * content: the generated agent carries the skill's own identity and points at
 * the SKILL.md the installer just wrote, so a skill edit reaches the agent on
 * the next install instead of drifting against a second copy.
 *
 * Frontmatter is read without the `yaml` package, which is a development
 * dependency the published CLI does not carry. The reader accepts the scalar
 * forms the skills actually use, and `tests/agents/skill-agent-definition.test.ts`
 * pins it against a real YAML parse of all nine.
 */

export interface SkillAgentDefinition {
  description: string;
  name: string;
  whenToUse: string;
}

/** Marks a file this CLI wrote, so a reinstall never overwrites a hand-authored one. */
export const generatedMarker = 'Generated by squad-skills';

const frontmatterPattern = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/;

export function readSkillAgentDefinition(source: string): SkillAgentDefinition | null {
  const frontmatter = source.match(frontmatterPattern)?.[1];

  if (frontmatter === undefined) return null;

  const name = readScalar(frontmatter, 'name');
  const description = readScalar(frontmatter, 'description');

  if (name === null || description === null) return null;

  return { description, name, whenToUse: readScalar(frontmatter, 'when_to_use') ?? '' };
}

/**
 * The body both formats share. Codex embeds this verbatim inside its TOML, the
 * same way the agent files it already ships do.
 */
export function renderAgentBody(
  definition: SkillAgentDefinition,
  installedSkillPath: string
): string {
  const description = [definition.description, definition.whenToUse]
    .filter((part) => part.length > 0)
    .join(' ');

  return `---
name: ${definition.name}
description: ${JSON.stringify(description)}
---

<!-- ${generatedMarker} from ${definition.name}/SKILL.md. Reinstalling regenerates it. -->

Read \`${installedSkillPath}\` and follow it for this task.

That file, together with the references it routes to, is the authoritative
definition of this role — its scope, its ownership boundaries, its handoff
contract, and its completion checklist. Read it before acting, and follow its
own routing rules to decide which of its references to open. Do not act on this
summary alone, and do not substitute your own process for the one it states.

If that file cannot be read, say so and stop rather than improvising the role.
`;
}

export function renderClaudeAgentFile(
  definition: SkillAgentDefinition,
  installedSkillPath: string
): string {
  return renderAgentBody(definition, installedSkillPath);
}

/**
 * Codex reads an agent from a TOML table whose `developer_instructions` holds
 * the whole Markdown definition. A literal string cannot escape its own
 * delimiter, so a body containing one is refused rather than silently
 * truncated; no shipped skill contains one and a test holds that.
 */
export function renderCodexAgentFile(
  definition: SkillAgentDefinition,
  installedSkillPath: string
): string {
  const body = renderAgentBody(definition, installedSkillPath);

  if (body.includes("'''")) {
    throw new Error(
      `${definition.name}: agent body contains ''' and cannot be written as a TOML literal string.`
    );
  }

  return `# ${generatedMarker}. Reinstalling regenerates this file.
[agents.${definition.name}]
developer_instructions = '''
${body}'''
`;
}

function readScalar(frontmatter: string, key: string): string | null {
  const line = frontmatter
    .split(/\r?\n/)
    .find((candidate) => candidate.startsWith(`${key}:`))
    ?.slice(key.length + 1)
    .trim();

  if (line === undefined || line.length === 0) return null;

  if (line.startsWith('"')) return JSON.parse(line) as string;
  if (line.startsWith("'")) return line.slice(1, -1).replaceAll("''", "'");

  return line;
}
