/**
 * Turns a packaged skill into an agent definition for Claude Code and Codex.
 *
 * The skill is the single source of truth. Nothing here restates a role's
 * content: the generated agent carries the skill's own identity and points at
 * the SKILL.md the installer just wrote, so a skill edit reaches the agent on
 * the next install instead of drifting against a second copy.
 *
 * Frontmatter is read without the `yaml` package, which is a development
 * dependency the published CLI does not carry. The reader accepts the scalar
 * forms the skills actually use, and `tests/agents/skill-agent-definition.test.ts`
 * pins it against a real YAML parse of every shipped skill.
 */

export interface SkillAgentDefinition {
  description: string;
  name: string;
  whenToUse: string;
}

/** Marks a file this CLI wrote, so a reinstall never overwrites a hand-authored one. */
export const generatedMarker = 'Generated by squad-skills';

const frontmatterPattern = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/;

export function readSkillAgentDefinition(source: string): SkillAgentDefinition | null {
  const frontmatter = source.match(frontmatterPattern)?.[1];

  if (frontmatter === undefined) return null;

  const name = readScalar(frontmatter, 'name');
  const description = readScalar(frontmatter, 'description');

  if (name === null || description === null) return null;

  return { description, name, whenToUse: readScalar(frontmatter, 'when_to_use') ?? '' };
}

/** How a generated agent reaches its skill, and what rewrites the file. */
export interface AgentBodyContext {
  /**
   * Extra frontmatter lines, already `key: value`. Only Claude Code's format
   * takes them: the plugin ships to every user, and Codex's agent table has no
   * model of its own. Empty for both.
   */
  frontmatter?: string[];
  /** The sentence telling the agent where its skill is. */
  instruction: string;
  /** What regenerates this file, for a reader who finds an edit gone. */
  origin: string;
}

/**
 * A caller's own machine preferences. Nothing in `skills/` names a model: this
 * package is installed by everyone, and the right model is a property of who is
 * running it, not of the role. They reach a generated file only when the
 * invocation that wrote it asked for them, which is what makes them survive the
 * reinstall that regenerates everything else.
 */
export interface AgentPreferences {
  effort?: string | null;
  model?: string | null;
}

/**
 * The body every format shares. Codex embeds it verbatim inside its TOML, the
 * same way the agent files it already ships do, and the plugin commits it as-is.
 */
export function renderAgentBody(
  definition: SkillAgentDefinition,
  context: AgentBodyContext
): string {
  const description = [definition.description, definition.whenToUse]
    .filter((part) => part.length > 0)
    .join(' ');

  const frontmatter = [
    `name: ${definition.name}`,
    `description: ${JSON.stringify(description)}`,
    ...(context.frontmatter ?? []),
  ];

  return `---
${frontmatter.join('\n')}
---

<!-- ${generatedMarker} from ${definition.name}/SKILL.md. ${context.origin} -->

${context.instruction}

That file, together with the references it routes to, is the authoritative
definition of this role — its scope, its ownership boundaries, its handoff
contract, and its completion checklist. Read it before acting, and follow its
own routing rules to decide which of its references to open. Do not act on this
summary alone, and do not substitute your own process for the one it states.

If that file cannot be read, say so and stop rather than improvising the role.
`;
}

export function renderClaudeAgentFile(
  definition: SkillAgentDefinition,
  installedSkillPath: string,
  preferences: AgentPreferences = {}
): string {
  return renderAgentBody(definition, {
    ...installedSkillContext(installedSkillPath),
    frontmatter: renderPreferenceLines(preferences),
  });
}

function renderPreferenceLines(preferences: AgentPreferences): string[] {
  const lines: string[] = [];

  if (preferences.model !== undefined && preferences.model !== null) {
    lines.push(`model: ${preferences.model}`);
  }

  if (preferences.effort !== undefined && preferences.effort !== null) {
    lines.push(`effort: ${preferences.effort}`);
  }

  return lines;
}

/**
 * The plugin variant names the skill instead of a path: a plugin installs its
 * skills and its agents together, so the agent can reach the skill by name and
 * the file stays valid wherever the plugin is unpacked.
 */
export function renderPluginAgentFile(definition: SkillAgentDefinition): string {
  return renderAgentBody(definition, {
    instruction: `Load the \`${definition.name}\` skill bundled with this plugin and follow it for this task.`,
    origin: 'Regenerated from that file; edits here are overwritten.',
  });
}

function installedSkillContext(installedSkillPath: string): AgentBodyContext {
  return {
    instruction: `Read \`${installedSkillPath}\` and follow it for this task.`,
    origin: 'Reinstalling regenerates it.',
  };
}

/**
 * Codex reads an agent from a TOML table whose `developer_instructions` holds
 * the whole Markdown definition. A literal string cannot escape its own
 * delimiter, so a body containing one is refused rather than silently
 * truncated; no shipped skill contains one and a test holds that.
 */
export function renderCodexAgentFile(
  definition: SkillAgentDefinition,
  installedSkillPath: string
): string {
  const body = renderAgentBody(definition, installedSkillContext(installedSkillPath));

  if (body.includes("'''")) {
    throw new Error(
      `${definition.name}: agent body contains ''' and cannot be written as a TOML literal string.`
    );
  }

  return `# ${generatedMarker}. Reinstalling regenerates this file.
[agents.${definition.name}]
developer_instructions = '''
${body}'''
`;
}

function readScalar(frontmatter: string, key: string): string | null {
  const line = frontmatter
    .split(/\r?\n/)
    .find((candidate) => candidate.startsWith(`${key}:`))
    ?.slice(key.length + 1)
    .trim();

  if (line === undefined || line.length === 0) return null;

  if (line.startsWith('"')) return JSON.parse(line) as string;
  if (line.startsWith("'")) return line.slice(1, -1).replaceAll("''", "'");

  return line;
}
